CREATE TABLE OBRA(
	ID 		CHARACTER(64) 	NOT NULL	PRIMARY KEY,
	NOME		CHARACTER(256)	NOT NULL,
	DESCRICAO	TEXT,
	ATIVO		INTEGER
);

CREATE TABLE PERFIL_COLABORADOR(
	ID 		CHARACTER(64) 	NOT NULL	PRIMARY KEY,
	ID_COLABORADOR	CHARACTER(64)	NOT NULL	REFERENCES	COLABORADOR(ID),
	ID_PERFIL	CHARACTER(64)	NOT NULL	REFERENCES	PERFIL(ID),
	ATIVO		INTEGER		NOT NULL
);

CREATE TABLE PERFIL(
	ID 		CHARACTER(64) 	NOT NULL	PRIMARY KEY,
	NOME		CHARACTER(256)	NOT NULL,
	DESCRICAO	TEXT
);


CREATE TABLE COLABORADOR(
	ID 		CHARACTER(64) 	NOT NULL	PRIMARY KEY,
	NOME		CHARACTER(256)	NOT NULL,
	USUARIO		CHARACTER(256)	NOT NULL,
	SENHA		CHARACTER(256)	NOT NULL,
	EMAIL		CHARACTER(256)	NOT NULL	
);

CREATE TABLE ALOCACAO(
	ID CHARACTER(64) NOT NULL PRIMARY KEY,
	ID_COLABORADOR	CHARACTER(64) NOT NULL REFERENCES COLABORADOR(ID),
	ID_OBRA CHARACTER(64) NOT NULL REFERENCES OBRA(ID),
	DATA_CRIACAO DATE NOT NULL,
	DATA_FIM DATE,
	DESCRICAO TEXT,
	ATIVO INTEGER
)

